name: CI - Build and Push to Artifact Registry

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout du code
      uses: actions/checkout@v4

    # 1. Authentification auprès de Google Cloud avec le Secret GCP_SA_KEY
    - name: Authentification Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    # 2. Configuration de Docker pour s'authentifier sur le registre de la région europe-west1
    - name: Configuration de Docker pour GCP
      run: gcloud auth configure-docker ${{ vars.ARTIFACT_LOCATION }}-docker.pkg.dev --quiet

# 3. Build et Push de l'image
    - name: Build et Push de l'image Docker
      run: |
        # Définition des deux tags
        IMAGE_TAG_SHA="${{ vars.ARTIFACT_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO_ID }}/quelpoke:${{ github.sha }}"
        IMAGE_TAG_LATEST="${{ vars.ARTIFACT_LOCATION }}-docker.pkg.dev/${{ vars.GCP_PROJECT_ID }}/${{ vars.ARTIFACT_REPO_ID }}/quelpoke:latest"
        
        echo "Construction de l'image..."
        # On ajoute les deux tags lors du build avec -t
        docker build -t $IMAGE_TAG_SHA -t $IMAGE_TAG_LATEST .
        
        echo "Envoi des images sur Artifact Registry..."
        docker push $IMAGE_TAG_SHA
        docker push $IMAGE_TAG_LATEST
